/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    According: typeof import('./src/components/According.vue')['default']
    CubicBezier: typeof import('./src/components/CubicBezier.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    DigitalAnimation: typeof import('./src/components/DigitalAnimation.vue')['default']
    Download: typeof import('./src/components/Download.vue')['default']
    ElevatorNavigation: typeof import('./src/components/ElevatorNavigation.vue')['default']
    FixedVirtualLists: typeof import('./src/components/FixedVirtualLists.vue')['default']
    FooterOpt: typeof import('./src/components/FooterOpt.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step: typeof import('./src/components/Step.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    Tabs1: typeof import('./src/components/tabs1.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Toast: typeof import('./src/components/Toast/index.vue')['default']
    VariableVirtualLists: typeof import('./src/components/VariableVirtualLists.vue')['default']
    WaveLoading: typeof import('./src/components/WaveLoading.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
